name: riverpod_test
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  very_good_analysis: ^4.0.0+1

dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.9.1
  mocktail: ^0.3.0
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  riverpod_generator: ^2.1.4
  test: ^1.24.1
