name: riverpod_test
description: A testing library which makes it easy to test providers. Built to be used with the riverpod state management package.
version: 0.1.0+1
publish_to: none
repository: https://github.com/egonm12/riverpod_test
issue_tracker: https://github.com/egonm12/riverpod_test/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  import_sorter: ^4.6.0
  very_good_analysis: ^4.0.0+1

dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.9.1
  mocktail: ^0.3.0
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  riverpod_generator: ^2.1.4
  test: ^1.24.1

import_sorter:
  comments: false
